### ISSUE TITLE
Skipped Video.

### ISSUE THREAD

**Issue by noobcoder2196** [kallqvist/skillshare-downloader#1]
The program skipped downloading video # 3 and went ahead with video # 4

![skillshare-download-bug1](https://user-images.githubusercontent.com/33173680/32420798-2f7960a2-c2b2-11e7-8054-63d847381c45.png)

What could be the reason for this? Also, is this tool specifically built for windows? I ask because I tweaked some of the code to include a variable that asks for the course url on running the script so that I don't have to manually paste the course url in the source code. So what I discovered was that when I downloaded a course that had a colon (:) in it's name, it gave me this error:

```
> C:\skillshare-download\code>example.py
> Enter Course URL:https://www.skillshare.com/classes/Mobile-Photography-Creating-
> Consistent-Look-and-Feel/158630588
> Traceback (most recent call last):
>   File "C:\skillshare-download\code\example.py", line 12, in <module>
>     dl.download_course_by_url(course_url)
>   File "C:\skillshare-download\code\downloader.py", line 24, in download_course_
> by_url
>     self.download_course_by_class_id(m.group(1))
>   File "C:\skillshare-download\code\downloader.py", line 42, in download_course_
> by_class_id
>     os.makedirs(base_path)
>   File "C:\Python27\lib\os.py", line 157, in makedirs
>     mkdir(name, mode)
> WindowsError: [Error 267] The directory name is invalid: '/data/ioegreer/Mobile
> Photography: Creating Consistent Look and Feel'
```

Windows does not allow a colon in its naming conventions. I suggest you replace every space and other special character(s) from the course name to a dash (-) so that windows doesn't complain about the naming. If I knew python better I'd do it myself but I  don't so please look this over as soon as you can.

Cheers mate. This tool will save me a ton of manually constructing URL's for each video using chromes network monitor :D (If I can get it to work :P )

**Comment by kallqvist** [comment]
Glad you like it :)
I haven't tried this on a windows box myself but other than the "colon in the filename" stuff (which I pushed a fix for btw, just pull the latest code) it shouldn't matter at all what system it runs on.

If you need more characters replaced, just check out the lines 61 and 62 for how to add more characters.

I'm not sure why it skipped a video for you and but when I wrote this the streaming service of skillshare was a bit random and sometimes just didn't work without any good reason at all...

Maybe if you just try the download again it will go through?
If not, you will probably have to build URL's and download the missing files manually, I don't have any subscription with skillshare currently so I sadly can't test this code anymore.

**Comment by noobcoder2196** [comment]
Alright, thanks for the update. :+1:

**Comment by kallqvist** [comment]
No problem, good luck!
