### ISSUE TITLE
download folder permissions

### ISSUE THREAD

**Issue by sutaj** [kallqvist/skillshare-downloader#10]
You need to change hard-coded path to download location. On Linux based system, you won't be able to download in to /data... change this to ../data or smth like that. Otherwise is working quite right...

**Comment by kallqvist** [comment]
That is a good idea for everyone running this outside of docker, fixed.

Path can also be changed either by param:
```
dl = Downloader(cookie="YOUR COOKIE", download_path="./anywhere/")
```

or environment variable:
```
export FILE_PATH="./anywhere/"
```
