### ISSUE TITLE
how use this bro im just a normal human

### ISSUE THREAD

**Issue by Coldang** [kallqvist/skillshare-downloader#11]
how open? please

**Comment by kallqvist** [comment]
Sorry dude, this is probably easiest to use if you already know a little bit of python... :/
Either you can try something along these steps:

1. Get python installed
2. Install all packages from requirements.txt (pip install -r requirements.txt)
3. Poke a little bit in example.py, add your skillshare cookie and adjust the URL for downloading
4. Run the code (python example.py)
5. Victory! :)

OR: I also know about this project, you might want to give it a try:
https://github.com/tharyckgusmao/Skill-Share-Crawler---DL
I have never tried it myself and have nothing to do with that code and/or developer in general but just from looking at it, it _might_ be a bit more user-friendly for everyone that is not a python developer.

Feel free to open new issues and add more details about your issue if any of these steps doesn't work
