### ISSUE TITLE
Ran into FIleNotFoundError

### ISSUE THREAD

**Issue by Suwadith** [kallqvist/skillshare-downloader#14]
> C:\Projects\skillshare-downloader\code>python example.py
Downloading C:\Projects\skillshare-downloader\code\data\fkane\data-science-and-machine-learning-with-python-hands-on/01 - introduction.mp4...
Traceback (most recent call last):
  File "example.py", line 10, in <module>
    dl.download_course_by_url('https://www.skillshare.com/classes/Data-Science-and-Machine-Learning-with-Python-Hands-On/1263657127')
  File "C:\Projects\skillshare-downloader\code\downloader.py", line 36, in download_course_by_url
    self.download_course_by_class_id(m.group(1))
  File "C:\Projects\skillshare-downloader\code\downloader.py", line 100, in download_course_by_class_id
    video_id=video_id,
  File "C:\Projects\skillshare-downloader\code\downloader.py", line 151, in download_video
    with open(fpath, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C\\Projects\\skillshare-downloader\\code\\data\\fkane\\data-science-and-machine-learning-with-python-hands-on/01 - introduction.mp4'

Am I doing something wrong?

**Comment by kallqvist** [comment]
Hmm, not sure yet :)

I see that there is a missing **:** in the path.
C\Projects instead of C:\Projects, try changing that if you have given it a custom download path that is missing that symbol.

If you haven't given it any different path then this is absolutely a problem in the code of this library that I have to fix.
I don't do any of my development on a windows computer so there haven't been too much testing done by me for these "windows style" file paths...

**Comment by Suwadith** [comment]
> Hmm, not sure yet :)
> 
> I see that there is a missing **:** in the path.
> C\Projects instead of C:\Projects, try changing that if you have given it a custom download path that is missing that symbol.
> 
> If you haven't given it any different path then this is absolutely a problem in the code of this library that I have to fix.
> I don't do any of my development on a windows computer so there haven't been too much testing done by me for these "windows style" file paths...

Yep that was the issue. 

I just commented out this line (#145) from **downloader.py**
`# fpath = re.sub(r'[*?:"<>|]',"",fpath)`

Now it works flawlessly with windows. 

Thanks a lot for pointing it out :)

**Comment by kallqvist** [comment]
Great! I don't remember exactly why that line was put there in the first place but I will make a mental note to fix this somehow so other people using windows don't have to get this same problem. :)

Thanks for pointing it out!

**Comment by Suwadith** [comment]
I guess the purpose of that line of code is to remove unwanted characters from the title of a particular skillshare course. 

In case if one the course's title end up having such reseverved characters then the program won't be able to make a default directory. 

I guess instead of using it on the fpath variable(full path) it'll be useful if you just use it only on the particular course's name. That can prevent this error from occuring no matter what the OS is. 

By the way great work with the application mate. Appreciate your efforts. 😃

**Comment by Suwadith** [comment]
My bad. Since you've already pointed out that you are using slugify I guess it'll be safe to remove that whole line of code 😅
