### ISSUE TITLE
How can I find my skillshare cookie?

### ISSUE THREAD

**Issue by Extreme-Z7** [kallqvist/skillshare-downloader#17]
The instruction on the ReadMe is quite confusing.

I've tried using both Firefox and Chrome and can't seem to find the mentioned 'document.cookie' anywhere in the development tools.

Without the right cookie, the app only downloads the first video and fails when it tries to download the rest.

**Comment by kallqvist** [comment]
Oh yes, sorry about that!
Haven't had much time to make a proper tutorial out of this yet... :/
There should be a 'console' tab or similar where you can type in commands and javascript code.
That is where you could get your cookie!

Here's what it should look like if you're using google chrome:
![cookie](https://user-images.githubusercontent.com/937404/52896052-c29d0e80-31c2-11e9-89cd-159ebe3fd687.jpg)

I blurred my cookie here, make sure you never share yours with anyone!
Then just copy-paste that entire value into the code.
But make sure to remove the **"** characters first!

It should look like this when you are done (I also blurred this one...):
![token-code](https://user-images.githubusercontent.com/937404/52896126-b2d1fa00-31c3-11e9-8e83-3bf2d3224f55.jpg)

Good luck!

**Comment by Extreme-Z7** [comment]
Sweet! I found it and it works perfectly now.

**Comment by rockethubble** [comment]
As of today, it is not working.

![image](https://user-images.githubusercontent.com/51690385/88017242-dc7d1680-cb57-11ea-82f8-0803b6fdca8a.png)
