### ISSUE TITLE
document.cookie not found

### ISSUE THREAD

**Issue by aerobo3** [kallqvist/skillshare-downloader#18]
Hey there, I am having an issue when I search for document.cookie in console. for some reason nothing shows up. Any help?

**Comment by kallqvist** [comment]
Hey, what browser do you use?
If chrome: check out this older issue for some screenshots of the process.
https://github.com/kallqvist/skillshare-downloader/issues/17

That is what it should look like when successful

**Comment by aerobo3** [comment]
Hey, I am using Chrome. But I have tried Chromium and Firefox to no avail. I seen that post and tried it, unfortunately nothing shows up for me in this place. I'll provide screenshots. 
![screen 2](https://user-images.githubusercontent.com/48299725/53967454-457b0000-40c3-11e9-85a4-7c3eaca243ca.PNG)
![screen 1](https://user-images.githubusercontent.com/48299725/53967456-457b0000-40c3-11e9-9884-e688ef07f28e.PNG)

**Comment by kallqvist** [comment]
Oh.. I see what's going on now.

You have to type that in a bit further down in that window, directly to the right of the blue >

**Comment by aerobo3** [comment]
Awesome, and I did that, and I do get something now, but the string does not start off the same as yours, does it need to be like that or is it completely personal?

**Comment by kallqvist** [comment]
Hmm, not sure... I guess it shouldn't matter exactly what it looks like as long as it's from skillshare but sadly there's really no way to know for sure other than running the code and see if videos fall out of the other end...

Just try to run the example.py script and download the URL that was in that file.
If there's something wrong with the cookie value still it will download the first video and then fail when trying to download the second one with some kind of "video not found" error.
If the cookie is correct they should all get downloaded.

There's not really any other way to know for sure...
Good luck!
