### ISSUE TITLE
"video_hashed_id": null, can this be fixed?

### ISSUE THREAD

**Issue by pendave** [kallqvist/skillshare-downloader#19]
"video_hashed_id": null, can this be fixed?

Such as for this course  https://www.skillshare.com/classes/Photoshop-CC-Masterclass-Foundations-Part-1/324272892

**Comment by kallqvist** [comment]
Yeah, sadly there's not any single way to try and solve this.
The part of the code where this happens pretty much just means "the skillshare server understood the request but doesn't want to return any video".

This is usually some problem with the cookie you have provided.
Have you been able to download any courses other than this one?
Also note that you need a premium skillshare subscription to be able to download premium courses.

Can you verify that cookie have been setup as described by the screenshots in issue #17 ?
