### ISSUE TITLE
Ability to download multiple classes at once

### ISSUE THREAD

**Issue by DarwishInDhaka** [kallqvist/skillshare-downloader#20]
Hey there!

I have been using the skillshare downloader and it works great, but I have a problem. I can't manually download the videos by editing it all the time since I have a large collection of classes to download.

I was wondering if there is a way to download multiple videos at once, it could be VERY handy. The program overall does the job fine and keep the great work up man!

**Comment by kallqvist** [comment]
Hey, glad you like it!

No, there's is not some built-in "automagic" way to download more classes than you specifically tell it but it is just python-code after all so should be easy to put something together yourself if you're up for the challenge. :)

A simple change like this would at least let you queue up a bunch of classes at once and then leave the computer to do the job.

`# download by class URL:
for url in [
    'https://www.skillshare.com/classes/Art-Fundamentals-in-One-Hour/189505397',
    'some other class url here',
    'and another one here, etc...',
]:
    dl.download_course_by_url(url)
`
