### ISSUE TITLE
KeyError: 'container'

### ISSUE THREAD

**Issue by ibmuhammadi** [kallqvist/skillshare-downloader#23]
When i execute the script i get this error 

Traceback (most recent call last):
  File "example.py", line 12, in <module>
    dl.download_course_by_class_id(387672280)
  File "/home/ibrahim/Downloads/pyles/sw/skillshare-downloader-master/code/downloader.py", line 100, in download_course_by_class_id
    video_id=video_id,
  File "/home/ibrahim/Downloads/pyles/sw/skillshare-downloader-master/code/downloader.py", line 140, in download_video
    if x['container'] == 'MP4' and 'src' in x:
KeyError: 'container'

**Comment by RoyceWhitaker** [comment]
Same here. Tried with python 2 & python 3

**Comment by maxwildcat** [comment]
i placed the following from downloader.py  inside an if 'container' in x and it worked locally 
''' 
note to non-programmers : 
    indentation is important in python :
    i recommend you edit in an IDE and/or make sure the line indentations are the same as below
#=========== condition moved inside the new IF ==================
           if x['container'] == 'MP4' and 'src' in x:
                dl_url = x['src']
                break
#=========== /condition moved inside the new IF ==================
#=========== New Code ==================
            # sometimes container is not found (quick and dirty - works locally - please check /test )
            if 'container' in x:
                if x['container'] == 'MP4' and 'src' in x:
                    dl_url = x['src']
                    break

**Comment by adityajoshi5** [comment]
Wow! Worked.

**Comment by XUBU365** [comment]
> Wow! Worked.

how can you please tell me the process

**Comment by adityajoshi5** [comment]
> > Wow! Worked.
> 
> how can you please tell me the process

@maxwildcat suggested replacing the first block he mentioned with the second.
First section is: 
`
           if x['container'] == 'MP4' and 'src' in x:
                dl_url = x['src']
                break
`
There is a possibility that some of the items might not contain the **container**. In that case, he suggest adding the line `if 'container' in x:` to skip reading these lines in such situations. Go to line #139 in **downloader.py**. 

If you are not from Python background, remember the extra spaces and tabs in the original comment.

**Comment by m6code** [comment]
> '''
> I placed the following from downloader.py inside an if 'container' in x and it worked locally
> 
> note to non-programmers :
> indentation is important in python :
> i recommend you edit in an IDE and/or make sure the line indentations are the same as below
> '''
> #=========== condition moved inside the new IF ==================
> 
> ```
>            if x['container'] == 'MP4' and 'src' in x:
>                 dl_url = x['src']
>                 break
> ```
> 
> #=========== /condition moved inside the new IF ==================
> #=========== New Code ==================
> 
> ```
>             # sometimes container is not found (quick and dirty - works locally - please check /test )
>             if 'container' in x:
>                 if x['container'] == 'MP4' and 'src' in x:
>                     dl_url = x['src']
>                     break
> ```
> 
> #=========== /New Code ==================

Thanks this worked for me
