### ISSUE TITLE
Is this still working in 2020?

### ISSUE THREAD

**Issue by inz002** [kallqvist/skillshare-downloader#28]
I have entered the cookie, but it still doesnt do anything.

**Comment by kallqvist** [comment]
I believe so yes, I no longer have a skillshare account of my own so I'm not able to actually test it but as far as I'm aware this is used by other people still.

Did you also update the example.py file and added the URLs for classes you wish to download?
That is the only way as I can remember that it wouldn't do anything at all, everything else should print some kind of error to your screen

**Comment by coozgan** [comment]
Hi I have tried the program but it doesn't return me anything. I seem to follow the cookie process but when I run the program doesnt run as it should be.

**Comment by kallqvist** [comment]
We're gonna need more info than that to be able to help you out.
Can you copy-paste some output from the script to here?
It normally prints a bunch of text when anything goes wrong

**Comment by denis-volin** [comment]
Yep, It's working fine
