### ISSUE TITLE
Just first video downloaded

### ISSUE THREAD

**Issue by alitekdemir** [kallqvist/skillshare-downloader#3]
```
Traceback (most recent call last):
  File "J:\Downloads\AverageSpatialSearch\main.py", line 10, in <module>
    dl.download_course_by_url('https://www.skillshare.com/classes/How-to-Make-Apps-with-No-Programming-Experience/1960310793')
  File "downloader.py", line 24, in download_course_by_url
    self.download_course_by_class_id(m.group(1))
  File "downloader.py", line 63, in download_course_by_class_id
    raise Exception('Failed to read video ID from data')
Exception: Failed to read video ID from data

```
I can not solve this problem. May be you can solve??

**Comment by alitekdemir** [comment]
if you want to test again, I can share my account with you :)
and thank you for your codes..

**Comment by kallqvist** [comment]
Sure, you can send an email to kallqvist@gmail.com and I'll take a look at it :)

**Comment by ptrfrncsmrph** [comment]
Any luck with this? I get:

**Comment by sandy2711323** [comment]
where are the videos downloaded ?

**Comment by kallqvist** [comment]
hey guys, sorry about all the silence from my end!
busy work have kept me away from github...

default download location in code is set to /data
this will most likely be an issue if you happen to try to run this on a windows machine

I really, _really_ do recommend anybody reading this to consider running it with docker and the docker-compose.yml project file in the repo.
That is how this all was developed and intended to be used.

Anyway, changing download path is pretty easy.
Edit the code and pass your path to the downloader class like this:
```
...
dl = Downloader(cookie=cookie, download_path='c:\path to downloads')
...
```

I only have mac/linux computers and can't test any of this on a windows machine.
Also; I don't even use or have a premium skillshare account anymore so sadly, I can't test any of this on any computer at all.
As far as development and improvements from my end is concerned I consider this project to be "dead", I'll leave the code online if anyone else happens to be interrested to see if it still works or maybe take on future development.

**Comment by kallqvist** [comment]
Oh; and for all that needs the ability to view skillshare courses offline but doesn't want to get their hands dirty writing code I know that there's also this project that might be a bit more stable and user-friendly:
https://github.com/tharyckgusmao/Skill-Share-Crawler---DL

My project is not a ready and user-friendly application for people to use, I don't have any relation or experience from this other project I'm linking to but just from the looks of it I'd say it's a more feature-rich and user-friendly projekt
