### ISSUE TITLE
TypeError: normalize() argument 2 must be unicode, not str

### ISSUE THREAD

**Issue by arukode** [kallqvist/skillshare-downloader#30]
Hello there!

I tried running the script and this what it says! I'm sorry but I'm a total noob at everything coding and I can't find a solution :( I think I got the right document.cookie, so I can't figure out what's wrong. Please help!

Thanks in advance.

**Comment by arukode** [comment]
Alright, I figured that I need to install requests and slugify, I did that on Terminal (I'm on Mac) and now it's giving me another error:

TypeError: normalize() argument 2 must be unicode, not str

And this on terminal:
WARNING: You are using pip version 19.2.3, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

Do I need to upgrade?

**Comment by arukode** [comment]
Another update, I'm sorry about this but it's been a learning curve and tracking back older issues has solved most of this (should've done in the first place, sorry about that!)

It's now working! Well, I don't know if this is may be the script or not (I'm a noob bear in mind!) but, even though I know I have a super-duper slow internet connection, but it seems that downloading with the script is even slower?

**Comment by ravinot** [comment]
@arukode Are you able to possibly share the document.cookie that you used? I've tried running this script, but get the following message back: "Exception: Fetch error, code == 403"

**Comment by kallqvist** [comment]
@ravinot no issue hijacking please, if you don't see the exception "TypeError: normalize() argument 2 must be unicode, not str" then you are in the wrong thread...
HTTP 403 means that your cookie is OK but your account is not, this can for instance happen if you try to download premium classes wihout paying for a premium account with skillshare

@arukode Did the issue with download speed get resolved or is it still the same? If not, please create a new issue for that, I've never experienced that issue myself but maybe someone else will be able to respond. ps. never share your cookie online
