### ISSUE TITLE
Exception: Failed to read video ID from data

### ISSUE THREAD

**Issue by mosambers** [kallqvist/skillshare-downloader#31]
Hello!

I always get after downloading the first video (the free preview) of a course, the following error:
Exception: Failed to read video ID from data

Thought that my cookie might be wrong but the free preview is also beeing downloaded without a cookie.

Need help, thank you!

**Comment by mosambers** [comment]
I found the reason. In the API only the video_hashed_id value from the first video is returned. The video_hashed_id values of the remaining videos are null.

But unfortunately I am not able to program another method to get the hash values.

**Comment by kallqvist** [comment]
Hey, yes this sounds like an issue with your cookie as far as I can tell at least...
Usually you get this result when there is something "wrong" with the cookie, either that it is formatted wrong somehow or that the account doesn't have access to view premium content at all.

Check out my screenshots in this previous issue: https://github.com/kallqvist/skillshare-downloader/issues/17

Can you confirm (without sharing/showing your cookie value to me or anyone else online of course) that your code is setup as in that example?

**Comment by mosambers** [comment]
Yes, you're right.I had copied the value of the cookie skillshare_user_ in the Chrome console under application --> storage -- > cookies, which is obviously wrong.

[
![skillshare](https://user-images.githubusercontent.com/13122993/79038860-1778c100-7bdd-11ea-9503-98bae5e25a0e.png)
](url)
Many thanks for the help!

**Comment by icxruus** [comment]
I have the same issue, I was able to download one course but not more. I checked the cookie and it's ok
