### ISSUE TITLE
Cannot find document.cookie

### ISSUE THREAD

**Issue by rockethubble** [kallqvist/skillshare-downloader#34]
I cannot execute the python script because I cannot find my cookie.

![image](https://user-images.githubusercontent.com/51690385/88019652-db021d00-cb5c-11ea-9abb-75f8914f39d6.png)

**Comment by AmirGhiasi95** [comment]
It seems like you're using Firefox. You need to find it in Console tab by typing  document.cookie  and then hit enter.
In case it's not found there, head over to Storage tab and find it there.

**Comment by rockethubble** [comment]
Hello thanks for replying. I am using Google Chrome.

I managed to find the cookie here;

1. I sign in to Skillshare. Watch a video
2. Right click, Inspect
3. 

![image](https://user-images.githubusercontent.com/51690385/88377547-fcb80a00-cdd1-11ea-8e7b-c340ffea51e7.png)
