### ISSUE TITLE
Please add feature to download subtitle with course video & multiple download at once

### ISSUE THREAD

**Issue by safiulbari** [kallqvist/skillshare-downloader#39]
add feature for:
1. English subtitle automatic
2. Multiple course download at once by multiple course id

**Comment by 04anubhavv** [comment]
https://github.com/kallqvist/skillshare-downloader/pull/51

subtitle fixed 

https://github.com/04anubhavv/skillshare-downloader

**Comment by safiulbari** [comment]
@04anubhavv

**Comment by safiulbari** [comment]
@04anubhavv

**Comment by safiulbari** [comment]
@04anubhavv want to download all videos by username. like url will be [skillshare .com / user /katro] download all video made by this teacher.

**Comment by 04anubhavv** [comment]
> @04anubhavv want to download all videos by username. like url will be [skillshare .com / user /katro] download all video made by this teacher.

I will try to add 👍
