### ISSUE TITLE
How to use the tool please

### ISSUE THREAD

**Issue by lshazly** [kallqvist/skillshare-downloader#5]
hello im not a developer and i need to run this because i want the courses to be on my laptop please

**Comment by Biggo6** [comment]
Hello! 

To use this tool is a bit technical, this needs you to have docker install and docker-compose in your local machine (PC) ,

which operating system are you using @lshazly ??

**Comment by Biggo6** [comment]
@lshazly ok good, i can give online support if you want please provide me your TeamViewer ID when you ready

**Comment by lshazly** [comment]
can you add me on skype?

**Comment by Biggo6** [comment]
add me skype @joramkimata

**Comment by lshazly** [comment]
i added u

**Comment by kallqvist** [comment]
Sorry for the silence from my end, haven't (have) no time for github at the moment.
Am crazy busy with my actual work... :/

Here's some extra information and thoughts from me in another issue:
https://github.com/kallqvist/skillshare-downloader/issues/3

I don't have a skillshare account and can't test/develop this any furter so I'm not able to be of much help to anyone.
Good luck!
