### ISSUE TITLE
Current working version of downloader code

### ISSUE THREAD

**Issue by andrewmk** [kallqvist/skillshare-downloader#67]
This is what I had to change the _download_course_by_class_id_ function to in _downloader.py_ in order to get it working again at the moment.

    def download_course_by_class_id(self, class_id):
        data = self.fetch_course_data_by_class_id(class_id=class_id)
        teacher_name = None

        if 'vanity_username' in data['_embedded']['teacher']:
            teacher_name = data['_embedded']['teacher']['vanity_username']

        if not teacher_name:
            teacher_name = data['_embedded']['teacher']['full_name']

        if not teacher_name:
            raise Exception('Failed to read teacher name from data')

        if self.is_unicode_string(teacher_name):
            teacher_name = teacher_name.encode('ascii', 'replace')

        title = data['title']

        if self.is_unicode_string(title):
            title = title.encode('ascii', 'replace')  # ignore any weird char

        base_path = os.path.abspath(
            os.path.join(
                self.download_path,
                slugify(teacher_name),
                slugify(title),
            )
        ).rstrip('/')

        if not os.path.exists(base_path):
            os.makedirs(base_path)

        for s in data['_embedded']['sessions']['_embedded']['sessions']:
            video_id = None

            if 'video_hashed_id' in s and s['video_hashed_id']:
                video_id = s['video_hashed_id'].split(':')[1]
            elif 'video_thumbnail_url' in s and s['video_thumbnail_url']:
                video_id = s['video_thumbnail_url'].split('/')[6]

            if not video_id:
                # NOTE: this happens sometimes...
                # seems random and temporary but might be some random
                # server-side check on user-agent etc?
                # ...think it's more stable now with those set to
                # emulate an android device
                raise Exception('Failed to read video ID from data')

            s_title = s['title']

            if self.is_unicode_string(s_title):
                s_title = s_title.encode('ascii', 'replace')  # ignore any weird char

            file_name = '{} - {}'.format(
                str(s['index'] + 1).zfill(2),
                slugify(s_title),
            )

            self.download_video(
                fpath='{base_path}/{session}.mp4'.format(
                    base_path=base_path,
                    session=file_name,
                ),
                video_id=video_id,
            )

            print('')

**Comment by ronnieops** [comment]
It didn't work for course '897276610'. :(

**Comment by andrewmk** [comment]
> It didn't work for course '897276610'. :(

Have you tried refreshing your login cookie? I seem to have to do that much more frequently than when I first started using skillshare about a year ago.

**Comment by ronnieops** [comment]
Yep, that was the issue. Every time it fails, I refresh the cookie and it works fine. It's funny because the "old" cookie works for others courses, but it fails with some. Go figure... But thanks!

**Comment by ogeeDeveloper** [comment]
only the first video I'm able to download I have tried refreshing the cookie multiple times

**Comment by andrewmk** [comment]
> only the first video I'm able to download I have tried refreshing the cookie multiple times

I was having trouble last night. Eventually I opened an incognito (private) browser window, logged in to SkillShare again and grabbed the cookie from there. Then it seemed to start working again. It might be worth trying that.

**Comment by ogeeDeveloper** [comment]
> > only the first video I'm able to download I have tried refreshing the cookie multiple times
> 
> I was having trouble last night. Eventually I opened an incognito (private) browser window, logged in to SkillShare again and grabbed the cookie from there. Then it seemed to start working again. It might be worth trying that.

Thanks I'll try this and see if it works

**Comment by ogeeDeveloper** [comment]
@andrewmk I tried getting the cookie in incognito mode but it doesn't work still

**Comment by andrewmk** [comment]
I no longer have a premium account so I can't test anything anymore. Sorry.

**Comment by ogeeDeveloper** [comment]
> I no longer have a premium account so I can't test anything anymore. Sorry.

Do u want a 7day account?

**Comment by zoliking** [comment]
Works like a charm, <3

**Comment by aximthered** [comment]
It seems there are two types of video_id (video_hashed_id of the video metadata) a 13 digit one (example: bc:6109186963001) and another 32 character one (example: df03d027d7f01a9a0e31c86f1e5a410d). The code only works if the video hash is 13 digit number. In case the hash is the 32 character string, the program throws the exception: failed to fetch video meta. 

I observed that in some courses all videos are hashed with 32 chars and in others a mixture of both 32 and 13. 

So simply adding a line to check if the length of the video_id is 13 and if so proceed with the download ensures that the program does not fail at the first instance of a 32 char hash. 

So what I did is replaced the self.download_video(.......) with this:

''' 
if (len(video_id) == 13):
    self.download_video(fpath='{base_path}/{session}.mp4'.format(base_path=base_path, session=file_name,), video_id=video_id, )
'''

If anyone finds a way to download the videos with 32 char hash let me know :P ,Thanks.

**Comment by KClaassen** [comment]
If I do do the replacement like that (correct me if I replaced it in wrong way):
""
if len(video_id) == 13:
                    self.download_video(
                        fpath="{base_path}/{session}.mp4".format(
                            base_path=base_path,
                            session=file_name,
                        ),
                        video_id=video_id,
                    )
""

Then when I run it, it says "Video already downloaded, skipping..." and finishes.

Is that because of the 32 char hash?

**Comment by andrewmk** [comment]
I think this discussion should be moved into a new issue as it appears to be a different change than the one I addressed with my code.
