### ISSUE TITLE
Cant download videos with non ASCII characters in title

### ISSUE THREAD

**Issue by MohammedAshker** [kallqvist/skillshare-downloader#9]
it's an absolute time saver, thanks a lot 

not able to download videos with non-ASCII characters in the title, tried converting to ASCII using sublime text, added UTF-8 as the coding in downloader.py, nothing helped can you suggest some workaround.

**Comment by kallqvist** [comment]
Glad you like it! :)

I've patched the code to "slugify" all titles and other strings that are used in filenames, I think this should fix your problem
